version: '3.8'

services:
  app:
    build: 
      context: ./
      dockerfile: ./Dockerfile
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app 
    environment:
      NODE_ENV: development
      DB_URI: mongodb://root:example@db:27017/devdb?authSource=admin
      SALT: 10
      ACCESS_TOKEN_SECRET: vetyvety
      REFRESH_TOKEN_SECRET: fjeiejwi
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

  db:
    image: mongo:latest
    volumes:
      - devdb:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: devdb
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.runCommand({ping: 1})' | mongosh --username root --password example --authenticationDatabase admin"]
      interval: 15s
      timeout: 10s
      retries: 10


volumes:
  devdb:
    driver: local
          