version: '3.8'

services:
  app:
    build: 
      context: ./
      dockerfile: ./Dockerfile
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app 
    environment:
      NODE_ENV: development
      DB_URI: mongodb://root:example@db:27017/devdb
    depends_on:
      - db
    links:
      - db

  db:
    image: mongo:latest
    volumes:
      - devdb:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: devdb


volumes:
  devdb:
    driver: local
          